# Generated by Django 4.1.6 on 2024-01-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('b_model', models.CharField(max_length=100)),
                ('b_reg_no', models.CharField(max_length=100)),
                ('s_type', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
