# Generated by Django 4.1.6 on 2023-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('email', models.EmailField(max_length=277, verbose_name='User Email')),
            ],
        ),
    ]
